'use strict';

module.exports = {
  'YARD WASTE PICKUP': 'Yard Waste Collection',
  'YARD WASTE UPGRADE': 'Yard Waste Collection',
  'YARD WASTE COLLECTION': 'Yard Waste Collection',
  'YARD WASTE BROKEN': 'Yard Waste Collection',
  'PICKUP YARD WASTE': 'Yard Waste Collection',
  'UPGRADE YARD WASTE': 'Yard Waste Collection',
  'COLLECTION YARD WASTE': 'Yard Waste Collection',
  'BROKEN YARD WASTE': 'Yard Waste Collection',
  'YARD WASTE MISSED': 'Missed Yard Waste',
  'MISSED YARD WASTE': 'Missed Yard Waste',
  'TRASH PICKUP': 'Missed Trash',
  'MISSED TRASH': 'Missed Trash',
  'TRASH COLLECTION': 'Missed Trash',
  'TRASH MISSED': 'Missed Trash',
  'PICKUP TRASH': 'Missed Trash',
  'COLLECTION TRASH': 'Missed Trash',
  'GARBAGE PICKUP': 'Missed Trash',
  'RUBBISH PICKUP': 'Missed Trash',
  'WASTE PICKUP': 'Missed Trash',
  'GARBAGE COLLECTION': 'Missed Trash',
  'RUBBISH COLLECTION': 'Missed Trash',
  'WASTE COLLECTION': 'Missed Trash',
  'GARBAGE MISSED': 'Missed Trash',
  'RUBBISH MISSED': 'Missed Trash',
  'WASTE MISSED': 'Missed Trash',
  'PICKUP GARBAGE': 'Missed Trash',
  'COLLECTION GARBAGE': 'Missed Trash',
  'MISSED GARBAGE': 'Missed Trash',
  'PICKUP RUBBISH': 'Missed Trash',
  'MISSED RUBBISH': 'Missed Trash',
  'COLLECTION RUBBISH': 'Missed Trash',
  'PICKUP WASTE': 'Missed Trash',
  'MISSED WASTE': 'Missed Trash',
  'COLLECTION WASTE': 'Missed Trash',
  'UPGRADE TRASH': 'Upgrade Trash Cart',
  'TRASH UPGRADE': 'Upgrade Trash Cart',
  'GARBAGE UPGRADE': 'Upgrade Trash Cart',
  'RUBBISH UPGRADE': 'Upgrade Trash Cart',
  'WASTE UPGRADE': 'Upgrade Trash Cart',
  'UPGRADE GARBAGE': 'Upgrade Trash Cart',
  'UPGRADE RUBBISH': 'Upgrade Trash Cart',
  'UPGRADE WASTE': 'Upgrade Trash Cart',
  'TRASH BROKEN': 'Broken Trash Cart',
  'BROKEN TRASH': 'Broken Trash Cart',
  'GARBAGE BROKEN': 'Broken Trash Cart',
  'RUBBISH BROKEN': 'Broken Trash Cart',
  'WASTE BROKEN': 'Broken Trash Cart',
  'BROKEN GARBAGE': 'Broken Trash Cart',
  'BROKEN RUBBISH': 'Broken Trash Cart',
  'BROKEN WASTE': 'Broken Trash Cart',
  'RECYCLING PICKUP': 'Missed Recycling',
  'RECYCLING COLLECTION': 'Missed Recycling',
  'RECYCLING MISSED': 'Missed Recycling',
  'PICKUP RECYCLING': 'Missed Recycling',
  'COLLECTION RECYCLING': 'Missed Recycling',
  'MISSED RECYCLING': 'Missed Recycling',
  'RECYCLING UPGRADE': 'Upgrade Recycling Cart',
  'UPGRADE RECYCLING': 'Upgrade Recycling Cart',
  'RECYCLING BROKEN': 'Broken Recycling Cart',
  'BROKEN RECYCLING': 'Broken Recycling Cart',
  'OIL PICKUP': 'Oil Collection',
  'OIL UPGRADE': 'Oil Collection',
  'OIL COLLECTION': 'Oil Collection',
  'OIL BROKEN': 'Oil Collection',
  'OIL MISSED': 'Oil Collection',
  'PICKUP OIL': 'Oil Collection',
  'UPGRADE OIL': 'Oil Collection',
  'COLLECTION OIL': 'Oil Collection',
  'BROKEN OIL': 'Oil Collection',
  'MISSED OIL': 'Oil Collection',
  'CARDBOARD PICKUP': 'Cardboard Collection',
  'CARDBOARD UPGRADE': 'Cardboard Collection',
  'CARDBOARD COLLECTION': 'Cardboard Collection',
  'CARDBOARD BROKEN': 'Cardboard Collection',
  'CARDBOARD MISSED': 'Cardboard Collection',
  'PICKUP CARDBOARD': 'Cardboard Collection',
  'UPGRADE CARDBOARD': 'Cardboard Collection',
  'COLLECTION CARDBOARD': 'Cardboard Collection',
  'BROKEN CARDBOARD': 'Cardboard Collection',
  'MISSED CARDBOARD': 'Cardboard Collection',
  'LEAF PICKUP': 'Leaf Collection',
  'LEAVES PICKUP': 'Leaf Collection',
  'LEAF UPGRADE': 'Leaf Collection',
  'LEAVES UPGRADE': 'Leaf Collection',
  'LEAF COLLECTION': 'Leaf Collection',
  'LEAVES COLLECTION': 'Leaf Collection',
  'LEAF BROKEN': 'Leaf Collection',
  'LEAVES BROKEN': 'Leaf Collection',
  'LEAF MISSED': 'Leaf Collection',
  'LEAVES MISSED': 'Leaf Collection',
  'PICKUP LEAF': 'Leaf Collection',
  'UPGRADE LEAF': 'Leaf Collection',
  'COLLECTION LEAF': 'Leaf Collection',
  'BROKEN LEAF': 'Leaf Collection',
  'MISSED LEAF': 'Leaf Collection',
  'PICKUP LEAVES': 'Leaf Collection',
  'UPGRADE LEAVES': 'Leaf Collection',
  'COLLECTION LEAVES': 'Leaf Collection',
  'BROKEN LEAVES': 'Leaf Collection',
  'MISSED LEAVES': 'Leaf Collection'
};
